### ISSUE TITLE
There might be a small typo in the baseline notebook.

### ISSUE THREAD

**Issue by AyushExel** [rasbt/nn_plus_gzip#1]
Thanks for the great work!
```
if not op.isfile("train.csv") and op.isfile("val.csv") and op.isfile("test.csv"):
```
this condition would never download the dataset right, as in a fresh system val and test won't be present by default. Atleast this happened for me, and I had to manually run download_data().

**Comment by rasbt** [comment]
Good catch, thanks. I forgot the parentheses 


```python
if not (op.isfile("train.csv") and op.isfile("val.csv") and op.isfile("test.csv")):
```

Fixed it!
